ALTER TABLE "Card" ADD COLUMN "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Card" ADD COLUMN "priority" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "Card" ADD COLUMN "labels" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Card" ADD COLUMN "dueDate" DATETIME;
